# Generated by Django 2.2.25 on 2022-03-23 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_view_log', '0002_auto_20160219_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageviewlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pageviewlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_view_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
